USE ecmss;

ALTER TABLE students ADD COLUMN avatar VARCHAR(500) DEFAULT NULL AFTER status;
ALTER TABLE counselors ADD COLUMN avatar VARCHAR(500) DEFAULT NULL AFTER status;
ALTER TABLE users ADD COLUMN avatar VARCHAR(500) DEFAULT NULL AFTER status;
